### PR TITLE
Adding `tbl_cmh()` function

### PR DESCRIPTION
**Pull request by ddsjoberg**
To do list for @aspina7 
- [ ] In the function's code, I commented a space where I feel additional checks on the function's arguments are warranted. I recommend you add them
- [ ] You had indicated the case or exposure status were flipped in the OR calculation. I did not change the original code.  I will leave it to you to check and update as needed.
- [ ] I did not write unit tests for the function. They should be added.
- [ ] I did not update NEWS or the version number. Update as you need for your project.

FYI, this code depends on the current dev version of gtsummary. After the next release, you can delete the `Remotes:` field for gtsummary in the DESCRIPTION file, and set the minimum version number required to 1.4.0. (Same for broom.helpers)

```r
gtsummary::trial %>%
    tbl_cmh(case = death, exposure = trt, strata = c(stage, grade))
```

image

### CODE REVIEW

**Comment by aspina7** [comment]
Thanks @ddsjoberg - will try find some time to sink my teeth in to this!

**Comment by ddsjoberg** [comment]
How is this coming along @aspina7 ?

**Comment by aspina7** [comment]
Sorry exam season at the moment so haven't got round to it yet. Planning to
sit down with it over next few weeks as have a break. Thx!

**Comment by aspina7** [comment]
only just sat down with this sorry, been through it now and the setup wrong making all the calculations wrong, will need to pull it apart and then put back together so will take me a little while longer- thanks!

**Comment by ddsjoberg** [comment]
@aspina7 there is no need to pull it apart and put it back together.  The OR calculations are relegated to `.calculate_unstrat_or()` and `.calculate_cmh_or()`. You just need to update these small helper functions to return the correct OR.

**Comment by aspina7** [comment]
yep seen those thanks - but the issue starts higher up as there should only be one stratifying variable and multiple exposure variables (not the other way round as currently setup). So need to fix the initial tbl_crosstabs and then get my head around how to re-arrange the layout so that can display crude, stratified and mh ratios appropriately (and calculate using the right bits). 
see this [page ](https://sphweb.bumc.bu.edu/otlt/mph-modules/bs/bs704-ep713_confounding-em/BS704-EP713_Confounding-EM7.html)for the math

**Comment by ddsjoberg** [comment]
> yep seen those thanks - but the issue starts higher up as there should only be one stratifying variable and multiple exposure variables (not the other way round as currently setup). So need to fix the initial tbl_crosstabs and then get my head around how to re-arrange the layout so that can display crude, stratified and mh ratios appropriately (and calculate using the right bits).
> see this [page ](https://sphweb.bumc.bu.edu/otlt/mph-modules/bs/bs704-ep713_confounding-em/BS704-EP713_Confounding-EM7.html)for the math

OK, I don't unserstand what you're going for. To me, this table looks exactly like the example you posted https://github.com/ddsjoberg/gtsummary/issues/679#issuecomment-748103953 (except one column of p-values is omitted).  I hope you can get what you want.

**Comment by ddsjoberg** [comment]
hey hey @aspina7 

this pull request has been open for quite some time now, and it appears on my GitHub list of things to do in that time. Feel free to re-purpose the code and merge if you'd like, but I am going to close the PR for now so it will no longer appear in my list.

**Comment by aspina7** [comment]
hey @ddsjoberg - sorry yes fair please do. Just constantly treading water at the moment, hoping to sit down with this over summer, will prod you when got something if thats ok please? Thanks!

**Comment by ddsjoberg** [comment]
> hey @ddsjoberg - sorry yes fair please do. Just constantly treading water at the moment, hoping to sit down with this over summer, will prod you when got something if thats ok please? Thanks!

of course, reach out when you're ready

**Pull request closed without merging**
